ARG STAGE_1
FROM ${STAGE_1} AS STAGE_2

WORKDIR /home/dependencies
RUN wget https://github.com/protocolbuffers/protobuf/releases/download/v3.17.3/protobuf-all-3.17.3.tar.gz -O /tmp/protobuf-all-3.17.3.tar.gz && \
        tar xzvf /tmp/protobuf-all-3.17.3.tar.gz && \
        cd protobuf-3.17.3 && \
        mkdir build && \
        cd build && \
        cmake ../cmake && \
        make && \
        make install