// Version.h generation, mirroring the CMake "Generate Version Information"
// section of CMakeLists.txt.
//
// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
//
// CMake reads the repo-root `version` file, appends `+<short git hash>` unless
// LOCALPROXY_RELEASE is set, and substitutes both strings into
// src/Version.h.in. `Version.h.in` double-indirects through
// ${${PROJECT_NAME}_VERSION_STRING_FULL} because CMakeLists.txt re-project()s
// when BUILD_TESTS is on; there is no equivalent indirection to reproduce
// here, so the two final macros are emitted directly. The generated header is
// byte-equivalent to what CMake produces.

const std = @import("std");

/// Read the repo-root `version` file (stripped).
fn readVersion(b: *std.Build) []const u8 {
    const raw = b.build_root.handle.readFileAlloc(
        b.graph.io,
        "version",
        b.allocator,
        .limited(64),
    ) catch |err| std.debug.panic(
        "unable to read the repo-root 'version' file: {s}",
        .{@errorName(err)},
    );
    return std.mem.trim(u8, raw, " \t\r\n");
}

/// `git rev-parse --short=7 HEAD`, or null when git is unavailable or this is
/// not a checkout. CMake swallows the same failure (ERROR_QUIET) and simply
/// omits the hash, so a tarball build stays reproducible.
fn gitShortHash(b: *std.Build) ?[]const u8 {
    const argv = [_][]const u8{
        "git",
        "-c",
        b.fmt("safe.directory={s}", .{b.build_root.path orelse "."}),
        "rev-parse",
        "--short=7",
        "HEAD",
    };
    // runAllowFail only writes out_code on failure and returns an error for a
    // non-zero exit, so a successful call needs no exit-code check.
    var code: u8 = 0;
    const stdout = b.runAllowFail(&argv, &code, .ignore) catch return null;
    const hash = std.mem.trim(u8, stdout, " \t\r\n");
    if (hash.len == 0) return null;
    return hash;
}

/// Emit `Version.h` into a generated directory and return that directory so
/// callers can put it on the include path. Matches CMake's
/// `include_directories(${PROJECT_BINARY_DIR})` behavior, where sources
/// `#include "Version.h"` unqualified.
pub fn generate(b: *std.Build, release: bool) std.Build.LazyPath {
    const version = readVersion(b);
    const short = b.fmt("v{s}", .{version});
    const full = if (release)
        short
    else if (gitShortHash(b)) |hash|
        b.fmt("v{s}+{s}", .{ version, hash })
    else
        short;

    const contents = b.fmt(
        \\// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
        \\// SPDX-License-Identifier: Apache-2.0
        \\
        \\/**
        \\ * Generated by build.zig at configure time; the CMake build generates the
        \\ * equivalent header from src/Version.h.in.
        \\ */
        \\#ifndef AWS_IOT_SECURE_TUNNELING_LOCAL_PROXY_VERSION_H
        \\#define AWS_IOT_SECURE_TUNNELING_LOCAL_PROXY_VERSION_H
        \\
        \\#define LOCAL_PROXY_VERSION_FULL "{s}"
        \\#define LOCAL_PROXY_VERSION "{s}"
        \\
        \\#endif // AWS_IOT_SECURE_TUNNELING_LOCAL_PROXY_VERSION_H
        \\
    , .{ full, short });

    std.debug.print(
        "-- AWS IoT Secure Tunneling Local Proxy version: {s}\n",
        .{full},
    );

    const wf = b.addWriteFiles();
    _ = wf.add("Version.h", contents);
    return wf.getDirectory();
}
